### ISSUE TITLE
 CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by gr-qft** [dabit3/next.js-amplify-workshop#9]
I've reached the step `npx serverless` and am seeing the following error

```
nextamplified › CredentialsError: Missing credentials in config
```

Would really appreciate it if someone could help with this.

Thanks!

**Comment by weisisheng** [comment]
You need to set up credentials in a manner that the serverless framework can use...which will then push to AWS.  Check this out--> https://www.serverless.com/framework/docs/providers/aws/guide/credentials/

**Comment by gr-qft** [comment]
@weisisheng 👍  Thanks so much for the info and the link. I followed the instructions and it worked.
